version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9
      - image: circleci/mongo:3.4.4
    environment:
      - MONGODB_URI: "mongodb://localhost:27017/checkin"
      - NODE_ENV: "test"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{checksum "package.json"}}
      - run: 
          name: Install NPM
          command: npm install
      - save_cache:
          key: dependency-cache-{{checksum "package.json"}}
          paths:
            - node_modules
      - run:
          name: Migrate DB
          command: npm run migrate

  test:
    docker:
      - image: circleci/node:8.9
      - image: circleci/mongo:3.4.4
    environment:
      - MONGODB_URI: "mongodb://localhost:27017/checkin"
    steps:
      - checkout
      - run:
          name: Test
          command: ./node_modules/.bin/gulp test

  deploy:
    machine:
      enabled: true
    environment:
      HEROKU_APP_NAME: tesc-checkin
    steps:
      - run:
          name: Run Setup Script
          command: bash .circleci/setup-heroku.sh
      - add_ssh_keys:
          fingerprints:
            - "d9:05:a8:9c:0c:23:0d:96:54:c7:8e:80:80:8d:cc:57"
      - run:
          name: Deploy Master to Heroku
          command: |
            git push --force git@heroku.com:$HEROKU_APP_NAME.git HEAD:refs/heads/master
            heroku restart
    
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test